export enum NewEventType {
    UPDATE_BALANCE = "UPDATE_BALANCE",
    PLAYGROUND_JOINED = "PLAYGROUND_JOINED",
    PLAYGROUND_EXITED = "PLAYGROUND_EXITED",
    PLAYER_STATUS_UPDATE = "PLAYER_STATUS_UPDATE",
    GAME_STARTED = "GAME_STARTED",
    GAME_ENDED = "GAME_ENDED",
    CREDIT_UPDATE = "CREDIT_UPDATE"
}