export enum NewEventType {
    UPDATE_BALANCE = "UPDATE_BALANCE",
    PLAYGROUND_JOINED = "PLAYGROUND_JOINED",
    PLAYGROUND_EXITED = "PLAYGROUND_EXITED",
    GAME_STARTED = "GAME_STARTED",
    GAME_ENDED = "GAME_ENDED",
    UPDATE_SPIN = "UPDATE_SPIN",
    UPDATE_PAYOUT = "UPDATE_PAYOUT",
    ALL_PLAYGROUND_PLAYERS = "ALL_PLAYGROUND_PLAYERS",
}