name: Build and Deploy

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
   
      - name: Push updated package.json to build-artifacts branch
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
           git fetch origin build-artifacts:build-artifacts
           git stash || echo "No changes to stash"
           git checkout build-artifacts
           git config user.name "TrippyRahul"
           git config user.email "rahulrawat.trippybug@gmail.com"
           rm -f package.json
           git checkout dev -- package.json
           git add package.json
           git diff --cached --quiet || git commit -m "update package.json" # Commit only if there are changes
           git push --force origin build-artifacts || echo "No changes to push"
           git stash pop || echo "No local changes to pop"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./dist/**/*.js
          
      - name: Force Update Root with New Build Files
        run: |
          
          # Remove existing app.js and src directory if they exist
          rm -rf ./app.js ./src
          git add .
          git commit -m "remove old builds"
          git push origin build-artifacts || echo "No changes to push"
          
          # Force copy new build files from dist to root directory
          cp -rf ./dist/src .  # -r flag for recursive copy of directories
          cp -f ./dist/app.js . # -f flag to force overwrite

          # Remove the dist directory after copying
          rm -rf ./dist
          
          # Stage changes and commit, forcing update of app.js and src
          git add .
          git commit -m "add new build files"
          git push origin build-artifacts || echo "No changes to push"
