name: Build and Deploy

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push updated dist folder to dev-build branch
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          # Fetch the dev-build branch if it exists
          git fetch origin dev-build || true

          # Create or switch to the dev-build branch
          if git show-ref --verify --quiet refs/heads/dev-build; then
              git checkout dev-build
          else
              git checkout -b dev-build
          fi

          # Configure Git user for committing
          git config user.name "Prathm0025"
          git config user.email "prathamesh@underpinservices.com"

          # Copy the new dist folder from the dev branch's workspace
          rm -rf dist  # Clear existing dist folder in dev-build
          cp -r dist/* .  # Copy the dist folder from the current workspace

          # Stage and commit the new dist folder in dev-build
          git add dist
          git commit -m "Update dist folder with new build" || echo "No changes to commit"
          git push --force origin dev-build
