name: Build and Deploy

on:
  push:
    branches:
      - "**" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        check-lastest : true
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist
        
    - name: Commit and Push Build Artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        git config --global user.name "${{ secrets.USERNAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        git add ./dist
        git commit -m 'added : build artifacts'
        git push origin HEAD
