name: Build and Deploy

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        check-latest: true
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Commit and Push Build Artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        git config --global user.name "TrippyRahul"
        git config --global user.email "rahulrawat.trippybug@gmail.com"
        git checkout -b build-artifacts
        git add -f ./dist
        git commit -m 'added: build artifacts'
        git push -u origin build-artifacts

  create_pull_request:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.create_pr.outputs.pull-request-number }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.G_TOKEN }}
        commit-message: 'added: build artifacts'
        branch: build-artifacts
        title: 'Add build artifacts'
        body: 'This pull request contains the build artifacts.'
        labels: 'auto-approve'

  auto_approve:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Pull Request
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.G_TOKEN }}
        pull-request-number: ${{ needs.create_pull_request.outputs.pull_request_number }}
